export const APP_CONFIG = {
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 10,
    SIZE_OPTIONS: [10, 25, 50, 100],
  },
  GAME: {
    POSITIONS: ["Top", "Jungle", "Mid", "Bot", "Support"] as const,
    LEAGUES: [
      "DCup",
      "TSC",
      "LEC",
      "LCKC",
      "LCO",
      "UL",
      "LLA",
      "LCK",
      "PRM",
      "LVP SL",
      "LFL",
      "PCS",
      "LJL",
      "VCS",
      "CBLOL",
      "LCS",
      "NACL",
      "LPL",
      "HM",
      "GLL",
      "ESLOL",
      "NLC",
      "TCL",
      "LIT",
      "LPLOL",
      "LDL",
      "EBL",
      "CBLOLA",
      "AL",
      "HC",
      "LFL2",
      "NEXO",
      "LRN",
      "LRS",
      "EM",
      "MSI",
      "LAS",
      "CT",
      "EPL",
      "EWC",
      "WLDs",
      "AC",
      "CDF",
      "PRMP",
      "USP",
      "HW",
      "NLC Aurora Open",
      "EBLPA",
      "GLLPA",
      "IC",
      "KeSPA",
    ] as const,
  },
} as const;

export const MESSAGES = {
  SUCCESS: {
    CREATE: (entity: string) => `${entity} created successfully`,
    UPDATE: (entity: string) => `${entity} updated successfully`,
    DELETE: (entity: string) => `${entity} deleted successfully`,
  },
  ERROR: {
    CREATE: (entity: string) => `Failed to create ${entity}`,
    UPDATE: (entity: string) => `Failed to update ${entity}`,
    DELETE: (entity: string) => `Failed to delete ${entity}`,
    LOAD: (entity: string) => `Failed to load ${entity}`,
  },
} as const;

export type Position = (typeof APP_CONFIG.GAME.POSITIONS)[number];
export type League = (typeof APP_CONFIG.GAME.LEAGUES)[number];
